// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/commands.dart';
import 'api/simple.dart';
import 'api/ui.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'system/dev.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<StreamSinkPacket> dco_decode_StreamSink_stream_sink_packet_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  GuiSender dco_decode_TraitDef_GuiSender(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DevInfo dco_decode_box_autoadd_dev_info(dynamic raw);

  @protected
  PacketFromEngine dco_decode_box_autoadd_packet_from_engine(dynamic raw);

  @protected
  StreamSinkPacket dco_decode_box_autoadd_stream_sink_packet(dynamic raw);

  @protected
  DevInfo dco_decode_dev_info(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  PacketFromEngine dco_decode_packet_from_engine(dynamic raw);

  @protected
  StreamSinkPacket dco_decode_stream_sink_packet(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<StreamSinkPacket> sse_decode_StreamSink_stream_sink_packet_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DevInfo sse_decode_box_autoadd_dev_info(SseDeserializer deserializer);

  @protected
  PacketFromEngine sse_decode_box_autoadd_packet_from_engine(
      SseDeserializer deserializer);

  @protected
  StreamSinkPacket sse_decode_box_autoadd_stream_sink_packet(
      SseDeserializer deserializer);

  @protected
  DevInfo sse_decode_dev_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PacketFromEngine sse_decode_packet_from_engine(SseDeserializer deserializer);

  @protected
  StreamSinkPacket sse_decode_stream_sink_packet(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_stream_sink_packet_Sse(
      RustStreamSink<StreamSinkPacket> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dev_info(DevInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_packet_from_engine(
      PacketFromEngine self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stream_sink_packet(
      StreamSinkPacket self, SseSerializer serializer);

  @protected
  void sse_encode_dev_info(DevInfo self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_packet_from_engine(
      PacketFromEngine self, SseSerializer serializer);

  @protected
  void sse_encode_stream_sink_packet(
      StreamSinkPacket self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
