// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DevInfo {
  final BigInt avgCycleTime;
  final BigInt maxCycleTime;
  final BigInt blockSize;
  final double sampleRate;
  final BigInt allowedCycleTime;
  final bool isFirstRun;

  const DevInfo({
    required this.avgCycleTime,
    required this.maxCycleTime,
    required this.blockSize,
    required this.sampleRate,
    required this.allowedCycleTime,
    required this.isFirstRun,
  });

  @override
  int get hashCode =>
      avgCycleTime.hashCode ^
      maxCycleTime.hashCode ^
      blockSize.hashCode ^
      sampleRate.hashCode ^
      allowedCycleTime.hashCode ^
      isFirstRun.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DevInfo &&
          runtimeType == other.runtimeType &&
          avgCycleTime == other.avgCycleTime &&
          maxCycleTime == other.maxCycleTime &&
          blockSize == other.blockSize &&
          sampleRate == other.sampleRate &&
          allowedCycleTime == other.allowedCycleTime &&
          isFirstRun == other.isFirstRun;
}
