// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../system/dev.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'commands.freezed.dart';

// These types are ignored because they are not used by any `pub` functions: `PacketFromUI`

@freezed
sealed class PacketFromEngine with _$PacketFromEngine {
  const PacketFromEngine._();

  const factory PacketFromEngine.position(
    BigInt field0,
  ) = PacketFromEngine_Position;
  const factory PacketFromEngine.buffer(
    Float32List field0,
  ) = PacketFromEngine_Buffer;
  const factory PacketFromEngine.debugInfo(
    DevInfo field0,
  ) = PacketFromEngine_DebugInfo;
  const factory PacketFromEngine.midiPorts(
    List<String> field0,
  ) = PacketFromEngine_MidiPorts;

  Future<String> getContent() =>
      RustLib.instance.api.crateApiCommandsPacketFromEngineGetContent(
        that: this,
      );

  Future<String> getDestination() =>
      RustLib.instance.api.crateApiCommandsPacketFromEngineGetDestination(
        that: this,
      );
}
