// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `ALREADY_LOADED`, `SENDER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `fmt`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `send_message`

Stream<StreamSinkPacket> runHandlerThread() =>
    RustLib.instance.api.crateApiUiRunHandlerThread();

abstract class GuiSender {
  Future<void> sendMessage({required StreamSinkPacket message});
}

class StreamSinkPacket {
  final String destination;
  final String content;

  const StreamSinkPacket({
    required this.destination,
    required this.content,
  });

  @override
  int get hashCode => destination.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamSinkPacket &&
          runtimeType == other.runtimeType &&
          destination == other.destination &&
          content == other.content;
}
